# Generated by Django 2.1.3 on 2020-07-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.AlterModelOptions(
            name='basedisc',
            options={'ordering': ['manufacturer', 'speed']},
        ),
        migrations.AddField(
            model_name='basedisc',
            name='style',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
