# Generated by Django 2.1.3 on 2020-07-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0002_auto_20200709_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedisc',
            name='img',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
